import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { dark } from '@clerk/themes'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
      <html lang="en" className='flex flex-col justify-center'>
        
        <ClerkProvider appearance={{
          baseTheme: dark,
        }}>
          <body className={inter.className}>
            <Header />
            <main className="container mx-auto">
              <div className="flex items-start justify-center min-h-screen">
                <div className="mt-20">
                  {children}
                </div>
              </div>
            </main>
            </body>
        </ClerkProvider>
      </html>
    
  )
}
